
  CREATE TABLE "FDMEE"."TEMPORARY_ANAGCIV" 
   (	"POSIZIONE" VARCHAR2(20 BYTE), 
	"SEZIONECIV" VARCHAR2(200 BYTE), 
	"CONTO" VARCHAR2(20 BYTE), 
	"TESTO_1" VARCHAR2(2100 BYTE), 
	"DA" VARCHAR2(20 BYTE), 
	"CONTO" VARCHAR2(20 BYTE), 
	"ENTITY" VARCHAR2(3000 BYTE),
	"CENTRODICOSTO" VARCHAR2(20 BYTE)
   ) 
